services:
  telegrambridge:
    build:
      dockerfile: ./infra/Dockerfile
    command: python -m telegrambridge
    env_file:
      - ./telegrambridge/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    logging:
      driver: journald
      options:
        tag: telegrambridge

  eventmanager:
    build:
      dockerfile: ./infra/Dockerfile
    command: python -m eventmanager
    depends_on:
      rabbitmq:
        condition: service_healthy 
    logging:
      driver: journald
      options:
        tag: eventmanager

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 3s
      retries: 5
    logging:
      driver: journald
      options:
        tag: rabbitmq
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass    
    logging:
      driver: journald
      options:
        tag: mongodb
         
volumes:
  rabbitmq_data:
  mongodb_data:
