services:
  telegrambridge:
    build:
      dockerfile: ./infra/Dockerfile
    command: python -m telegrambridge
    env_file:
      - ./telegrambridge/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  matcher:
    build:
      dockerfile: ./infra/Dockerfile
    command: python -m matcher
    depends_on:
      rabbitmq:
        condition: service_healthy 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  rabbitmq_data:
